### ISSUE TITLE
Thread.setContextClassLoader could be relevant

### ISSUE THREAD

**Issue by hanslovsky** [scijava/scyjava#2]
@ctrueden  Do you think that [Thread.setContextClassLoader](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.html#setContextClassLoader(java.lang.ClassLoader)) is relevant for this?

**Comment by hanslovsky** [comment]
This might be relevant as well:
https://stackoverflow.com/questions/18354535/why-do-subsequent-jni-threads-return-null-on-currentthread-getclassloader

**Comment by hanslovsky** [comment]
Might be relevant, too. Cannot invoke `Name.class` in python, though.

**Comment by hanslovsky** [comment]
I tried to set the system class loader, but no success. Similar to this:
https://stackoverflow.com/questions/5380275/replacement-system-classloader-for-classes-in-jars-containing-jars

**Comment by hanslovsky** [comment]
https://stackoverflow.com/a/16302771/1725687

**Comment by hanslovsky** [comment]
[`-Djava.system.class.loader=`](https://stackoverflow.com/questions/11395074/what-loads-the-java-system-classloader) doesn't help either

**Comment by ctrueden** [comment]
jgo is working well for now, so we close this. No need for fully dynamic after-the-fact class loading at this time.
