### ISSUE TITLE
Python 2.7 Support

### ISSUE THREAD

**Issue by evbo** [scijava/scyjava#6]
This project is such a great idea! But, would you be open to (a contribution) making this compatible with Python 2.7?

Typically, java code I work with is commonly legacy, and so naturally I'm usually running it on legacy systems as well, where python 3 maybe isn't yet being used. So having scyjava for python 2.7 would be amazing!

**Comment by evbo** [comment]
this is a total hack, but it's at least a prototype. I've used [3to2](https://pypi.org/project/3to2/) for converting the syntax of convert.py to python 2. I then swapped out `collections.Collection` for a 2.7 friendly `collections.deque`

Those were the only changes necessary for me to pull a Java map type (that's all I need currently) and iterate it by it's keys. Sadly, any iteration of the `items()` fails with:

```
to_python(arc_map).items()
```
tail of stack trace:
```
def __contains__(self, item):
RuntimeError: maximum recursion depth exceeded
```

I instead am still happy just doing:

```
keys = to_python(java_map.keySet())
for key in keys:
    value = java_map.get(key)
```


See attached conversion of scyjava that is running the above examples for me using python 2.7

Any thoughts or guidance on a cleaner approach? 

[convert.txt](https://github.com/scijava/scyjava/files/2654627/convert.txt)

**Comment by evbo** [comment]
yes - pyjnius works in python 2

It's been 6 months since I last tried, but if I'm remembering correctly conda has glibc requirements that prevents my environment from using the latest version.

as for python 2 end of life, I think you have a good point. The only flip side to that argumen is "end of life" doesn't always mean "end of existence". But, I respect your decision to leave python 2 in the past. Just my 2 cents here. Still this is a great library! Thanks!

**Comment by ctrueden** [comment]
@hanslovsky and I agree we aren't going to support Python 2. Sorry @evbo. Please feel welcome to fork. We don't expect a lot of big changes to this component any time soon.
