### ISSUE TITLE
How to import java class into python

### ISSUE THREAD

**Issue by chautuankien** [scijava/scyjava#61]
I have folder branch like below:
```
.../importer/

xml.py
xml_parser folder:
+CMXLFile.java
```

I am using scyjava.jimport to import CMXLFile java class from CMXLFile.java into xml.py My code is below:

```python
def read_XML_file(xml_file_path):
    ij = imagej.init()
    print(f"ImageJ version: {ij.getVersion()}")
    config.add_classpath("...\Fiji.app\jars\ij-1.53t.jar")

    CXMLFile = jimport('xml_parser.CXMLFile.CXMLFile')
    print(CXMLFile)
    cxmlfile = CXMLFile()
    imp = cxmlfile.Reader(xml_file_path)

    return imp
```

I get the error: `TypeError: Class xml_parser.CXMLFile.CXMLFile is not found`
So, My question is: How to import java class into python?

**Comment by ctrueden** [comment]
@chautuankien You need to compile your `.java` code to a `.class` file first, and ensure it is on Java's classpath.

```shell
javac xml_parser/CXMLFile.java
```
And then you will have an `xml_parser/CXMLFile.class` in the `xml_parser` directory.

Then put the base directory (`.../importer`) on the classpath before initializing PyImageJ:

Make sure you get the spelling right—in your post above, you wrote `CXML` in some places and `CMXL` in others.

```python
import imagej
import scyjava.config
from scyjava import jimport

scyjava.config.add_classpath(".../importer")
ij = imagej.init()  # Do you need Fiji? If so, use `imagej.init('sc.fiji:fiji')` instead, or wrap a local Fiji.app folder.
CXMLFile = jimport('xml_parser.CXMLFile')
print(CXMLFile)
cxmlfile = CXMLFile()
imp = cxmlfile.Reader(xml_file_path)
```
