### ISSUE TITLE
Several issues running make test on osx-arm64 machine

### ISSUE THREAD

**Issue by jschneidereit** [scijava/scyjava#66]
👋 I was trying to set up this repo to make a contribution or two and ran tests from main and noticed a few issues:

1. (actually before `make test`) `flake8-typing-imports` for osx-arm64 hasn't been uploaded to conda-forge
2. the `java_heap.py` tests use `5 MB` for comparing used memory, which I guess doesn't work well on these M chips since the memory used on my laptop was `6 MB` 😂 

P.S. for some comedy check out my too many repos issue [blunder](https://github.com/imagej/pyimagej/issues/310)

**Comment by elevans** [comment]
Thanks @jschneidereit. It looks like you are correct in that the `flake8-typing-imports` package is missing builds for osx-arm64 on conda-forge:

```bash
$ mamba search flake8-typing-imports --platform osx-arm64
Loading channels: done
No match found for: flake8-typing-imports. Search: *flake8-typing-imports*
The following packages are not available from current channels:

  - flake8-typing-imports

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  ```

I did a quick google search and it looks like there are spurious reports on various forums discussing higher than expected JVM memory usage on Apple Silicon. I'm guessing you've probably run into the same thing.
